import type { Metadata } from "next";
import "./globals.css";
import Header from "./_components/Header";
import { inter, roboto } from "./fonts";


export const metadata: Metadata = {
  title: "NextJS",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} ${roboto.className} mx-auto antialiased`}
      >
        <header>
          <Header />
        </header>
        <main className="mt-12">{children}</main>
      </body>
    </html>
  );
}
